spring.application.name=smart-expense-tracker


# Server port
server.port=8080

# MongoDB local connection
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=smart_expense_tracker

# JWT configuration
jwt.secret=ThisIsASecretKeyForSmartExpenseTrackerProject2026MustBeLongEnough
jwt.expiration=86400000

# Gmail SMTP configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abcd@gmail.com             
spring.mail.password=12345
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# add the senders mail to it this "spring.mail.username=absce@gamil.com" and the password you have enter the throught
# through the, after 2 step verifcation and then you will create a google app password...search create google app password
# ust  like for this mail ash15edu15@gmail.com ..ii am using this password jpvkohpaotmzrsdu;
#eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhc2hAZ21haWwuY29tIiwidXNlcklkIjoiNmE0YTBlZjBjNGRjZTE3MjczZmNiMTdhIiwibmFtZSI6IkFzaHV0b3NoIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODMyMzk0OTYsImV4cCI6MTc4MzMyNTg5Nn0.NAi0x42INAPTZdnuDNngX4bCq7yayC0e-BWZFioVOQBlKSHbHIuB-OcfvkANsIbai-n-dWi55jJp0OcpkelovQ